[package]
name = "irc_proto"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = {version = "1.8.0"}
log = "0.4.27"
env_logger = {version = "0.11"}
tokio = { version = "1.44.2", features = ["full"] }
